{
  continuationUnwindTest(new CallbackReceiver<Integer>(){
    public Integer receive(    final Callback<Integer> continuation){
      continuation.handleException(new MyException());
      throw new AssertionError();
    }
  }
);
}
